service: swift-service

provider:
  name: openwhisk
  runtime: swift

functions:
  ping:
    handler: ping.main
    events:
      - http:
          path: ping
          method: get


plugins:
  - serverless-openwhisk
