service: python-service

provider:
  name: openwhisk
  runtime: python

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get

plugins:
  - serverless-openwhisk
